//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPUtils.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAPUtils.__Internal.I18N.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The add-on has not been initialized,.
        /// </summary>
        internal static string AddontNotInitializedException_AddontNotInitializedException_The_add_on_has_not_been_initialized_ {
            get {
                return ResourceManager.GetString("AddontNotInitializedException_AddontNotInitializedException_The_add_on_has_not_be" +
                        "en_initialized_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported in IAuditable.
        /// </summary>
        internal static string AuditableField_GetUserTableField__0__is_not_supported_in_IAuditable {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField__0__is_not_supported_in_IAuditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string AuditableField_GetUserTableField_Active {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at date.
        /// </summary>
        internal static string AuditableField_GetUserTableField_Created_at_date {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField_Created_at_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at time.
        /// </summary>
        internal static string AuditableField_GetUserTableField_Created_at_time {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField_Created_at_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string AuditableField_GetUserTableField_Created_by {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField_Created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string AuditableField_GetUserTableField_Inactive {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated at date.
        /// </summary>
        internal static string AuditableField_GetUserTableField_Updated_at_date {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField_Updated_at_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated at time.
        /// </summary>
        internal static string AuditableField_GetUserTableField_Updated_at_time {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField_Updated_at_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        internal static string AuditableField_GetUserTableField_Updated_by {
            get {
                return ResourceManager.GetString("AuditableField_GetUserTableField_Updated_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BooleanFieldAttribute_ValidValues_No {
            get {
                return ResourceManager.GetString("BooleanFieldAttribute_ValidValues_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BooleanFieldAttribute_ValidValues_Yes {
            get {
                return ResourceManager.GetString("BooleanFieldAttribute_ValidValues_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_AddContextMenuItems_Add_row {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_AddContextMenuItems_Add_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete row.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_AddContextMenuItems_Delete_row {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_AddContextMenuItems_Delete_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding context menu: {0}.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_AddContextMenuItems_Error_adding_context_menu___0_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_AddContextMenuItems_Error_adding_context_menu___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore row.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_AddContextMenuItems_Restore_row {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_AddContextMenuItems_Restore_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_Application_MenuEvent_Cancel {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_Application_MenuEvent_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes.
        ///Do you want to reload and discard the changes?.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_Application_MenuEvent_There_are_unsaved_changes__Do_you_want_to_reload_and_discard_the_changes_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_Application_MenuEvent_There_are_unsaved_changes__Do_you_w" +
                        "ant_to_reload_and_discard_the_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_Application_MenuEvent_Yes {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_Application_MenuEvent_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files {0}.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ChooseOpenPath_Excel_files__0_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ChooseOpenPath_Excel_files__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel file.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ChooseOpenPath_Import_Excel_file {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ChooseOpenPath_Import_Excel_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files {0}.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ChooseSavePath_Excel_files__0_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ChooseSavePath_Excel_files__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Excel.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ChooseSavePath_Save_Excel {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ChooseSavePath_Save_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [State].
        /// </summary>
        internal static string ChangeTrackerMatrixForm_CustomInitializeComponent__State_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_CustomInitializeComponent__State_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_CustomInitializeComponent_Code {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_CustomInitializeComponent_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_CustomInitializeComponent_Name {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_CustomInitializeComponent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed: {0}.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ExportToExcel_Export_completed___0_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ExportToExcel_Export_completed___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ExportToExcel_OK {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ExportToExcel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ExportToExcel_Open {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ExportToExcel_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Excel could not be generated: {0}.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ExportToExcel_The_Excel_could_not_be_generated___0_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ExportToExcel_The_Excel_could_not_be_generated___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_GenerateExcel_Invalid_value {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_GenerateExcel_Invalid_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_GenerateExcel_No {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_GenerateExcel_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only dates are allowed..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_GenerateExcel_Only_dates_are_allowed_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_GenerateExcel_Only_dates_are_allowed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only decimal numbers are allowed..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_GenerateExcel_Only_decimal_numbers_are_allowed_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_GenerateExcel_Only_decimal_numbers_are_allowed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only integers are allowed..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_GenerateExcel_Only_integers_are_allowed_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_GenerateExcel_Only_integers_are_allowed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of decimal places must be between 0 and 6..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_GenerateExcel_The_number_of_decimal_places_must_be_between_0_and_6_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_GenerateExcel_The_number_of_decimal_places_must_be_betwee" +
                        "n_0_and_6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_GenerateExcel_Yes {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_GenerateExcel_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ImportFromExcel_Cancel {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ImportFromExcel_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ImportFromExcel_Continue {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ImportFromExcel_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read Excel: {0}.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ImportFromExcel_Could_not_read_Excel___0_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ImportFromExcel_Could_not_read_Excel___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Do you want to discard the changes?.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ImportFromExcel_There_are_unsaved_changes__Do_you_want_to_discard_the_changes_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ImportFromExcel_There_are_unsaved_changes__Do_you_want_to" +
                        "_discard_the_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_OnFormCloseBefore_Cancel {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_OnFormCloseBefore_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes.
        ///Do you want to save before closing?.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_OnFormCloseBefore_There_are_unsaved_changes__Do_you_want_to_save_before_closing_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_OnFormCloseBefore_There_are_unsaved_changes__Do_you_want_" +
                        "to_save_before_closing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_OnFormCloseBefore_Yes {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_OnFormCloseBefore_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Excel. Please generate the Excel file using the export button...
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ParseExcel_Invalid_Excel__Please_generate_the_Excel_file_using_the_export_button__ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ParseExcel_Invalid_Excel__Please_generate_the_Excel_file_" +
                        "using_the_export_button__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Excel file. Please generate the Excel file using the export button..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ParseExcel_Invalid_Excel_file__Please_generate_the_Excel_file_using_the_export_button_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ParseExcel_Invalid_Excel_file__Please_generate_the_Excel_" +
                        "file_using_the_export_button_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain the sheet &apos;{0}&apos;. Please generate the Excel file using the export button..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_ParseExcel_The_file_does_not_contain_the_sheet___0____Please_generate_the_Excel_file_using_the_export_button_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_ParseExcel_The_file_does_not_contain_the_sheet___0____Ple" +
                        "ase_generate_the_Excel_file_using_the_export_button_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreloadData Thread Data Loaded.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_PreloadDataAsync_PreloadData_Thread_Data_Loaded {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_PreloadDataAsync_PreloadData_Thread_Data_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreloadData Thread Started.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_PreloadDataAsync_PreloadData_Thread_Started {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_PreloadDataAsync_PreloadData_Thread_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preloading data....
        /// </summary>
        internal static string ChangeTrackerMatrixForm_PreloadDataAsync_Preloading_data___ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_PreloadDataAsync_Preloading_data___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_SaveButtonOnClickAfter_No {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_SaveButtonOnClickAfter_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be saved.
        ///Do you want to continue?.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_SaveButtonOnClickAfter_The_changes_will_be_saved__Do_you_want_to_continue_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_SaveButtonOnClickAfter_The_changes_will_be_saved__Do_you_" +
                        "want_to_continue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ChangeTrackerMatrixForm_SaveButtonOnClickAfter_Yes {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_SaveButtonOnClickAfter_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changes have been saved..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_SaveChanges__0__changes_have_been_saved_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_SaveChanges__0__changes_have_been_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changes have been saved. {1} changes have failed..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_SaveChanges__0__changes_have_been_saved___1__changes_have_failed_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_SaveChanges__0__changes_have_been_saved___1__changes_have" +
                        "_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes could not be saved..
        /// </summary>
        internal static string ChangeTrackerMatrixForm_SaveChanges_Changes_could_not_be_saved_ {
            get {
                return ResourceManager.GetString("ChangeTrackerMatrixForm_SaveChanges_Changes_could_not_be_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Code was provided for new data in {0}, but PrimaryKeyStrategy was set to Manual..
        /// </summary>
        internal static string CodeNotSetException_CodeNotSetException_No_Code_was_provided_for_new_data_in__0___but_PrimaryKeyStrategy_was_set_to_Manual_ {
            get {
                return ResourceManager.GetString("CodeNotSetException_CodeNotSetException_No_Code_was_provided_for_new_data_in__0__" +
                        "_but_PrimaryKeyStrategy_was_set_to_Manual_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Parsing.
        /// </summary>
        internal static string ColumnParser_FormatDtValue_Unknown_Parsing {
            get {
                return ResourceManager.GetString("ColumnParser_FormatDtValue_Unknown_Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string ConsoleLogger_PrintExceptionToConsole__0____1_ {
            get {
                return ResourceManager.GetString("ConsoleLogger_PrintExceptionToConsole__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caused by: .
        /// </summary>
        internal static string ConsoleLogger_PrintExceptionToConsole_Caused_by__ {
            get {
                return ResourceManager.GetString("ConsoleLogger_PrintExceptionToConsole_Caused_by__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        internal static string ConsoleLogger_PrintExceptionToConsole_File___0_ {
            get {
                return ResourceManager.GetString("ConsoleLogger_PrintExceptionToConsole_File___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: {0}.
        /// </summary>
        internal static string ConsoleLogger_PrintExceptionToConsole_Line___0_ {
            get {
                return ResourceManager.GetString("ConsoleLogger_PrintExceptionToConsole_Line___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurred in: {0}.{1}.
        /// </summary>
        internal static string ConsoleLogger_PrintExceptionToConsole_Occurred_in___0___1_ {
            get {
                return ResourceManager.GetString("ConsoleLogger_PrintExceptionToConsole_Occurred_in___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        internal static string ConsoleLogger_PrintExceptionToConsole_Stack_Trace_ {
            get {
                return ResourceManager.GetString("ConsoleLogger_PrintExceptionToConsole_Stack_Trace_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParseValue should not be used on DateTimeFieldAttribute. Use the specialized handling for SAP date/time fields..
        /// </summary>
        internal static string DateTimeFieldAttribute_ParseValue_ParseValue_should_not_be_used_on_DateTimeFieldAttribute__Use_the_specialized_handling_for_SAP_date_time_fields_ {
            get {
                return ResourceManager.GetString("DateTimeFieldAttribute_ParseValue_ParseValue_should_not_be_used_on_DateTimeFieldA" +
                        "ttribute__Use_the_specialized_handling_for_SAP_date_time_fields_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToSapData should not be used on DateTimeFieldAttribute. Use the specialized handling for SAP date/time fields..
        /// </summary>
        internal static string DateTimeFieldAttribute_ToSapData_ToSapData_should_not_be_used_on_DateTimeFieldAttribute__Use_the_specialized_handling_for_SAP_date_time_fields_ {
            get {
                return ResourceManager.GetString("DateTimeFieldAttribute_ToSapData_ToSapData_should_not_be_used_on_DateTimeFieldAtt" +
                        "ribute__Use_the_specialized_handling_for_SAP_date_time_fields_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized date format..
        /// </summary>
        internal static string FormatInfo_GetDateFullFormat_Unrecognized_date_format_ {
            get {
                return ResourceManager.GetString("FormatInfo_GetDateFullFormat_Unrecognized_date_format_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time value (ODBC-1031) [131-183].
        /// </summary>
        internal static string FormUtils_ValidateTimeCell_Invalid_time_value__ODBC_1031___131_183_ {
            get {
                return ResourceManager.GetString("FormUtils_ValidateTimeCell_Invalid_time_value__ODBC_1031___131_183_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with code {0} already exists in table {1}..
        /// </summary>
        internal static string ItemAlreadyExistException_ItemAlreadyExistException_Item_with_code__0__already_exists_in_table__1__ {
            get {
                return ResourceManager.GetString("ItemAlreadyExistException_ItemAlreadyExistException_Item_with_code__0__already_ex" +
                        "ists_in_table__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with code {1} does not exist in table {2}..
        /// </summary>
        internal static string ItemDoNotExistException_ItemDoNotExistException__0__with_code__1__does_not_exist_in_table__2__ {
            get {
                return ResourceManager.GetString("ItemDoNotExistException_ItemDoNotExistException__0__with_code__1__does_not_exist_" +
                        "in_table__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file {0}: {1}.
        /// </summary>
        internal static string Logger_CleanOldLogs_Could_not_delete_file__0____1_ {
            get {
                return ResourceManager.GetString("Logger_CleanOldLogs_Could_not_delete_file__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar el archivo {0}: {1}.
        /// </summary>
        internal static string Logger_CleanOldLogs_No_se_pudo_eliminar_el_archivo__0____1_ {
            get {
                return ResourceManager.GetString("Logger_CleanOldLogs_No_se_pudo_eliminar_el_archivo__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error.
        /// </summary>
        internal static string Logger_Critical_Critical_error {
            get {
                return ResourceManager.GetString("Logger_Critical_Critical_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string Logger_Error_Unknown_error {
            get {
                return ResourceManager.GetString("Logger_Error_Unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caused by: {0}: {1}.
        /// </summary>
        internal static string Logger_ExceptionToString_Caused_by___0____1_ {
            get {
                return ResourceManager.GetString("Logger_ExceptionToString_Caused_by___0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        internal static string Logger_ExceptionToString_File___0_ {
            get {
                return ResourceManager.GetString("Logger_ExceptionToString_File___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: {0}.
        /// </summary>
        internal static string Logger_ExceptionToString_Line___0_ {
            get {
                return ResourceManager.GetString("Logger_ExceptionToString_Line___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurred in: {0}.{1}.
        /// </summary>
        internal static string Logger_ExceptionToString_Occurred_in___0___1_ {
            get {
                return ResourceManager.GetString("Logger_ExceptionToString_Occurred_in___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        internal static string Logger_ExceptionToString_Stack_Trace_ {
            get {
                return ResourceManager.GetString("Logger_ExceptionToString_Stack_Trace_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [ERROR FORMATTING ARGUMENTS]: {1}.
        /// </summary>
        internal static string Logger_Format__0___ERROR_FORMATTING_ARGUMENTS____1_ {
            get {
                return ResourceManager.GetString("Logger_Format__0___ERROR_FORMATTING_ARGUMENTS____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Logger_GetLogFilePath_Company {
            get {
                return ResourceManager.GetString("Logger_GetLogFilePath_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path contains invalid characters: {fullPath}.
        /// </summary>
        internal static string Logger_GetLogFilePath_The_path_contains_invalid_characters___fullPath_ {
            get {
                return ResourceManager.GetString("Logger_GetLogFilePath_The_path_contains_invalid_characters___fullPath_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Logger_GetLogFilePath_User {
            get {
                return ResourceManager.GetString("Logger_GetLogFilePath_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not serializable to XML] {0}. ToString(): {1}.
        /// </summary>
        internal static string Logger_Log__Not_serializable_to_XML___0___ToString_____1_ {
            get {
                return ResourceManager.GetString("Logger_Log__Not_serializable_to_XML___0___ToString_____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string Logger_Log__null {
            get {
                return ResourceManager.GetString("Logger_Log__null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Object: {0}]{1}{2}.
        /// </summary>
        internal static string Logger_Log__Object___0___1__2_ {
            get {
                return ResourceManager.GetString("Logger_Log__Object___0___1__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON error: {0}.
        /// </summary>
        internal static string Logger_Logger_JSON_error___0_ {
            get {
                return ResourceManager.GetString("Logger_Logger_JSON_error___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Logger] Error writing log: {0}.
        /// </summary>
        internal static string Logger_ProcessLogQueue__Logger__Error_writing_log___0_ {
            get {
                return ResourceManager.GetString("Logger_ProcessLogQueue__Logger__Error_writing_log___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving LogSettings file: {0}.
        /// </summary>
        internal static string LogSettings_Instance_Error_saving_LogSettings_file___0_ {
            get {
                return ResourceManager.GetString("LogSettings_Instance_Error_saving_LogSettings_file___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error applying CFL on matrix: {0}.
        /// </summary>
        internal static string MatrixExtensions_CflSubscriber_Error_applying_CFL_on_matrix___0_ {
            get {
                return ResourceManager.GetString("MatrixExtensions_CflSubscriber_Error_applying_CFL_on_matrix___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option..
        /// </summary>
        internal static string ObjectViewerForm_AddButtonClickAfter_Invalid_option_ {
            get {
                return ResourceManager.GetString("ObjectViewerForm_AddButtonClickAfter_Invalid_option_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ObjectViewerForm_AddButtonClickAfter_No {
            get {
                return ResourceManager.GetString("ObjectViewerForm_AddButtonClickAfter_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ObjectViewerForm_AddButtonClickAfter_Yes {
            get {
                return ResourceManager.GetString("ObjectViewerForm_AddButtonClickAfter_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change this document after you have added it. Continue?.
        /// </summary>
        internal static string ObjectViewerForm_AddButtonClickAfter_You_cannot_change_this_document_after_you_have_added_it__Continue_ {
            get {
                return ResourceManager.GetString("ObjectViewerForm_AddButtonClickAfter_You_cannot_change_this_document_after_you_ha" +
                        "ve_added_it__Continue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp; Close.
        /// </summary>
        internal static string ObjectViewerForm_ObjectViewerForm_Add___Close {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ObjectViewerForm_Add___Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp; New.
        /// </summary>
        internal static string ObjectViewerForm_ObjectViewerForm_Add___New {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ObjectViewerForm_Add___New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp; View.
        /// </summary>
        internal static string ObjectViewerForm_ObjectViewerForm_Add___View {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ObjectViewerForm_Add___View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ObjectViewerForm_ShowObjectSelector_Cancel {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ShowObjectSelector_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ObjectViewerForm_ShowObjectSelector_Code {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ShowObjectSelector_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ObjectViewerForm_ShowObjectSelector_Error___0_ {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ShowObjectSelector_Error___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ObjectViewerForm_ShowObjectSelector_Name {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ShowObjectSelector_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string ObjectViewerForm_ShowObjectSelector_Select {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ShowObjectSelector_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Object.
        /// </summary>
        internal static string ObjectViewerForm_ShowObjectSelector_Select_Object {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ShowObjectSelector_Select_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a row..
        /// </summary>
        internal static string ObjectViewerForm_ShowObjectSelector_You_must_select_a_row_ {
            get {
                return ResourceManager.GetString("ObjectViewerForm_ShowObjectSelector_You_must_select_a_row_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if menu item {0} exists.
        /// </summary>
        internal static string SapAddon_AddMenuItem_Checking_if_menu_item__0__exists {
            get {
                return ResourceManager.GetString("SapAddon_AddMenuItem_Checking_if_menu_item__0__exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item {0} is Sap Menu, skipping..
        /// </summary>
        internal static string SapAddon_AddMenuItem_Menu_item__0__is_Sap_Menu__skipping_ {
            get {
                return ResourceManager.GetString("SapAddon_AddMenuItem_Menu_item__0__is_Sap_Menu__skipping_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing menu item {0}.
        /// </summary>
        internal static string SapAddon_AddMenuItem_Removing_menu_item__0_ {
            get {
                return ResourceManager.GetString("SapAddon_AddMenuItem_Removing_menu_item__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting menu item {0}&apos;s image.
        /// </summary>
        internal static string SapAddon_AddMenuItem_Setting_menu_item__0__s_image {
            get {
                return ResourceManager.GetString("SapAddon_AddMenuItem_Setting_menu_item__0__s_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding menu folder {0}.
        /// </summary>
        internal static string SapAddon_AddMenuItems_Adding_menu_folder__0_ {
            get {
                return ResourceManager.GetString("SapAddon_AddMenuItems_Adding_menu_folder__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding menu folder {0} item.
        /// </summary>
        internal static string SapAddon_AddMenuItems_Adding_menu_folder__0__item {
            get {
                return ResourceManager.GetString("SapAddon_AddMenuItems_Adding_menu_folder__0__item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding menu item {0}.
        /// </summary>
        internal static string SapAddon_AddMenuItems_Adding_menu_item__0_ {
            get {
                return ResourceManager.GetString("SapAddon_AddMenuItems_Adding_menu_item__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create DateTimeFieldAttribute Field in System Table, use Date and Time instead..
        /// </summary>
        internal static string SapAddon_AddSapTableUserField_Cannot_create_DateTimeFieldAttribute_Field_in_System_Table__use_Date_and_Time_instead_ {
            get {
                return ResourceManager.GetString("SapAddon_AddSapTableUserField_Cannot_create_DateTimeFieldAttribute_Field_in_Syste" +
                        "m_Table__use_Date_and_Time_instead_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating BoCreatableObjectType.cot_MenuCreationParams.
        /// </summary>
        internal static string SapAddon_CreateMenu_Creating_BoCreatableObjectType_cot_MenuCreationParams {
            get {
                return ResourceManager.GetString("SapAddon_CreateMenu_Creating_BoCreatableObjectType_cot_MenuCreationParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Menus Object.
        /// </summary>
        internal static string SapAddon_CreateMenu_Get_Menus_Object {
            get {
                return ResourceManager.GetString("SapAddon_CreateMenu_Get_Menus_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Menu Item by id {0}.
        /// </summary>
        internal static string SapAddon_CreateMenu_Getting_Menu_Item_by_id__0_ {
            get {
                return ResourceManager.GetString("SapAddon_CreateMenu_Getting_Menu_Item_by_id__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Menus.
        /// </summary>
        internal static string SapAddon_CreateMenu_Loading_Menus {
            get {
                return ResourceManager.GetString("SapAddon_CreateMenu_Loading_Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting new Menus ItemPosition to last index if no position is set.
        /// </summary>
        internal static string SapAddon_CreateMenu_Setting_new_Menus_ItemPosition_to_last_index_if_no_position_is_set {
            get {
                return ResourceManager.GetString("SapAddon_CreateMenu_Setting_new_Menus_ItemPosition_to_last_index_if_no_position_i" +
                        "s_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to Application.MenuEvent.
        /// </summary>
        internal static string SapAddon_CreateMenu_Subscribing_to_Application_MenuEvent {
            get {
                return ResourceManager.GetString("SapAddon_CreateMenu_Subscribing_to_Application_MenuEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new menu could not be created. Error: .
        /// </summary>
        internal static string SapAddon_CreateMenu_The_new_menu_could_not_be_created__Error__ {
            get {
                return ResourceManager.GetString("SapAddon_CreateMenu_The_new_menu_could_not_be_created__Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new menu could not be created. Error: {0}.
        /// </summary>
        internal static string SapAddon_CreateMenu_The_new_menu_could_not_be_created__Error___0_ {
            get {
                return ResourceManager.GetString("SapAddon_CreateMenu_The_new_menu_could_not_be_created__Error___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} already exist.
        /// </summary>
        internal static string SapAddon_CreateUserTable_Table__0__already_exist {
            get {
                return ResourceManager.GetString("SapAddon_CreateUserTable_Table__0__already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} created.
        /// </summary>
        internal static string SapAddon_CreateUserTable_Table__0__created {
            get {
                return ResourceManager.GetString("SapAddon_CreateUserTable_Table__0__created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user table {0}. Error {1}.
        /// </summary>
        internal static string SapAddon_CreateUserTable_Unable_to_add_user_table__0___Error__1_ {
            get {
                return ResourceManager.GetString("SapAddon_CreateUserTable_Unable_to_add_user_table__0___Error__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying if table {0} already exist.
        /// </summary>
        internal static string SapAddon_CreateUserTable_Verifying_if_table__0__already_exist {
            get {
                return ResourceManager.GetString("SapAddon_CreateUserTable_Verifying_if_table__0__already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0}.{1} already exist.
        /// </summary>
        internal static string SapAddon_CreateUserTableField_Field__0___1__already_exist {
            get {
                return ResourceManager.GetString("SapAddon_CreateUserTableField_Field__0___1__already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0}.{1} created.
        /// </summary>
        internal static string SapAddon_CreateUserTableField_Field__0___1__created {
            get {
                return ResourceManager.GetString("SapAddon_CreateUserTableField_Field__0___1__created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add field {0} to table {1}. Error {2}.
        /// </summary>
        internal static string SapAddon_CreateUserTableField_Unable_to_add_field__0__to_table__1___Error__2_ {
            get {
                return ResourceManager.GetString("SapAddon_CreateUserTableField_Unable_to_add_field__0__to_table__1___Error__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying if field {0}.{1} already exist.
        /// </summary>
        internal static string SapAddon_ExistTableField_Verifying_if_field__0___1__already_exist {
            get {
                return ResourceManager.GetString("SapAddon_ExistTableField_Verifying_if_field__0___1__already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files generated:
        ///{0}
        ///{1}.
        /// </summary>
        internal static string SapAddon_GenerateSetupFiles_Files_Generated {
            get {
                return ResourceManager.GetString("SapAddon_GenerateSetupFiles_Files_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .csproj file was found in the executable path or parent folders.
        /// </summary>
        internal static string SapAddon_GenerateSetupFiles_No__csproj_file_was_found_in_the_executable_path_or_parent_folders {
            get {
                return ResourceManager.GetString("SapAddon_GenerateSetupFiles_No__csproj_file_was_found_in_the_executable_path_or_p" +
                        "arent_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating user table: {0}.
        /// </summary>
        internal static string SapAddon_InitializeUserTables_Creating_user_table___0_ {
            get {
                return ResourceManager.GetString("SapAddon_InitializeUserTables_Creating_user_table___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing field: {0}.{1}.
        /// </summary>
        internal static string SapAddon_InitializeUserTables_Processing_field___0___1_ {
            get {
                return ResourceManager.GetString("SapAddon_InitializeUserTables_Processing_field___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing table: {0}.
        /// </summary>
        internal static string SapAddon_InitializeUserTables_Processing_table___0_ {
            get {
                return ResourceManager.GetString("SapAddon_InitializeUserTables_Processing_table___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapAddon instance not found.
        /// </summary>
        internal static string SapAddon_Instance_SapAddon_instance_not_found {
            get {
                return ResourceManager.GetString("SapAddon_Instance_SapAddon_instance_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing add-on initialization.
        /// </summary>
        internal static string SapAddon_Run_Finishing_add_on_initialization {
            get {
                return ResourceManager.GetString("SapAddon_Run_Finishing_add_on_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running SAP Add-on.
        /// </summary>
        internal static string SapAddon_Run_Running_SAP_Add_on {
            get {
                return ResourceManager.GetString("SapAddon_Run_Running_SAP_Add_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on could not be initialized.
        /// </summary>
        internal static string SapAddon_SapAddon_Add_on_could_not_be_initialized {
            get {
                return ResourceManager.GetString("SapAddon_SapAddon_Add_on_could_not_be_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Add-on Initialized.
        /// </summary>
        internal static string SapAddon_SapAddon_SAP_Add_on_Initialized {
            get {
                return ResourceManager.GetString("SapAddon_SapAddon_SAP_Add_on_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke {0} related method.
        /// </summary>
        internal static string SapAddon_SBO_Application_MenuEvent_Invoke__0__related_method {
            get {
                return ResourceManager.GetString("SapAddon_SBO_Application_MenuEvent_Invoke__0__related_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBO_Application_MenuEvent called with pval.MenuUID {0}.
        /// </summary>
        internal static string SapAddon_SBO_Application_MenuEvent_SBO_Application_MenuEvent_called_with_pval_MenuUID__0_ {
            get {
                return ResourceManager.GetString("SapAddon_SBO_Application_MenuEvent_SBO_Application_MenuEvent_called_with_pval_Men" +
                        "uUID__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property `{1}` markes as Ignored.
        /// </summary>
        internal static string SapAddon_ValidateFields__0__Property__1__Marked_as_Ignored {
            get {
                return ResourceManager.GetString("SapAddon_ValidateFields__0__Property__1__Marked_as_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserTableField {0}.{1} is not valid. Expected property type: {2}, but got: {3}.
        /// </summary>
        internal static string SapAddon_ValidateFields_IUserTableField__0___1__is_not_valid__Expected_property_type___2___but_got___3_ {
            get {
                return ResourceManager.GetString("SapAddon_ValidateFields_IUserTableField__0___1__is_not_valid__Expected_property_t" +
                        "ype___2___but_got___3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserTableField not found in {0}.{1}.
        /// </summary>
        internal static string SapAddon_ValidateFields_IUserTableField_not_found_in__0___1_ {
            get {
                return ResourceManager.GetString("SapAddon_ValidateFields_IUserTableField_not_found_in__0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not assignable From IUserTableObjectModel.
        /// </summary>
        internal static string SapAddon_ValidateTable__0__is_not_assignable_From_IUserTableObjectModel {
            get {
                return ResourceManager.GetString("SapAddon_ValidateTable__0__is_not_assignable_From_IUserTableObjectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTable Attribute not found in class {0}.
        /// </summary>
        internal static string SapAddon_ValidateTable_UserTable_Attribute_not_found_in_class__0_ {
            get {
                return ResourceManager.GetString("SapAddon_ValidateTable_UserTable_Attribute_not_found_in_class__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying table {0} implements UserTableObjectModel.
        /// </summary>
        internal static string SapAddon_ValidateTable_Verifying_table__0__implements_UserTableObjectModel {
            get {
                return ResourceManager.GetString("SapAddon_ValidateTable_Verifying_table__0__implements_UserTableObjectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying table {0} has Attribute UserTableAttribute.
        /// </summary>
        internal static string SapAddon_ValidateTable_Veryfing_table__0__has_Attribute_UserTableAttribute {
            get {
                return ResourceManager.GetString("SapAddon_ValidateTable_Veryfing_table__0__has_Attribute_UserTableAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key not known for table &apos;{0}&apos;..
        /// </summary>
        internal static string SapUtils_GetPrimaryKey_Primary_key_not_known_for_table___0___ {
            get {
                return ResourceManager.GetString("SapUtils_GetPrimaryKey_Primary_key_not_known_for_table___0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key not known for table &apos;{0}&apos;..
        /// </summary>
        internal static string SapUtils_GetReadableColumn_Primary_key_not_known_for_table___0___ {
            get {
                return ResourceManager.GetString("SapUtils_GetReadableColumn_Primary_key_not_known_for_table___0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table not known for Object Type: &apos;{0}&apos;..
        /// </summary>
        internal static string SapUtils_GetTableNameFromObjectType_Table_not_known_for_Object_Type____0___ {
            get {
                return ResourceManager.GetString("SapUtils_GetTableNameFromObjectType_Table_not_known_for_Object_Type____0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported comparison: {0}.
        /// </summary>
        internal static string SqlWhereBuilder_BuildGroup_Unsupported_comparison___0_ {
            get {
                return ResourceManager.GetString("SqlWhereBuilder_BuildGroup_Unsupported_comparison___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete.
        /// </summary>
        internal static string StatusExtensions_GetReadableName_Delete {
            get {
                return ResourceManager.GetString("StatusExtensions_GetReadableName_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Discard.
        /// </summary>
        internal static string StatusExtensions_GetReadableName_Discard {
            get {
                return ResourceManager.GetString("StatusExtensions_GetReadableName_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Modify.
        /// </summary>
        internal static string StatusExtensions_GetReadableName_Modify {
            get {
                return ResourceManager.GetString("StatusExtensions_GetReadableName_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ New.
        /// </summary>
        internal static string StatusExtensions_GetReadableName_New {
            get {
                return ResourceManager.GetString("StatusExtensions_GetReadableName_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Normal.
        /// </summary>
        internal static string StatusExtensions_GetReadableName_Normal {
            get {
                return ResourceManager.GetString("StatusExtensions_GetReadableName_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔁 Restore.
        /// </summary>
        internal static string StatusExtensions_GetReadableName_Restore {
            get {
                return ResourceManager.GetString("StatusExtensions_GetReadableName_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values must be provided in (value, description) pairs..
        /// </summary>
        internal static string UserFieldValidValue_ParseValidValuePairs_Valid_values_must_be_provided_in__value__description__pairs_ {
            get {
                return ResourceManager.GetString("UserFieldValidValue_ParseValidValuePairs_Valid_values_must_be_provided_in__value_" +
                        "_description__pairs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing form with UID: {0}.
        /// </summary>
        internal static string UserForm_Close_Closing_form_with_UID___0_ {
            get {
                return ResourceManager.GetString("UserForm_Close_Closing_form_with_UID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling format search for form with UID: {0}.
        /// </summary>
        internal static string UserForm_EnableFormatSearch_Enabling_format_search_for_form_with_UID___0_ {
            get {
                return ResourceManager.GetString("UserForm_EnableFormatSearch_Enabling_format_search_for_form_with_UID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting menu {0} enabled state to {1} for form with UID: {2}.
        /// </summary>
        internal static string UserForm_EnableMenu_Setting_menu__0__enabled_state_to__1__for_form_with_UID___2_ {
            get {
                return ResourceManager.GetString("UserForm_EnableMenu_Setting_menu__0__enabled_state_to__1__for_form_with_UID___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting form freeze state to {0} for form with UID: {1}.
        /// </summary>
        internal static string UserForm_Freeze_Setting_form_freeze_state_to__0__for_form_with_UID___1_ {
            get {
                return ResourceManager.GetString("UserForm_Freeze_Setting_form_freeze_state_to__0__for_form_with_UID___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting XML representation of form with UID: {0}.
        /// </summary>
        internal static string UserForm_GetAsXML_Getting_XML_representation_of_form_with_UID___0_ {
            get {
                return ResourceManager.GetString("UserForm_GetAsXML_Getting_XML_representation_of_form_with_UID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing existing form with UID: {0}.
        /// </summary>
        internal static string UserForm_LoadForm_Closing_existing_form_with_UID___0_ {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Closing_existing_form_with_UID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not close form {0}.
        /// </summary>
        internal static string UserForm_LoadForm_Could_not_close_form__0_ {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Could_not_close_form__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during form loading: .
        /// </summary>
        internal static string UserForm_LoadForm_Error_during_form_loading__ {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Error_during_form_loading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form is not valid.
        /// </summary>
        internal static string UserForm_LoadForm_Form_is_not_valid {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Form_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form loaded successfully.
        /// </summary>
        internal static string UserForm_LoadForm_Form_loaded_successfully {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Form_loaded_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form node has no attributes.
        /// </summary>
        internal static string UserForm_LoadForm_Form_node_has_no_attributes {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Form_node_has_no_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form node not found in XML file.
        /// </summary>
        internal static string UserForm_LoadForm_Form_node_not_found_in_XML_file {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Form_node_not_found_in_XML_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form type set to: {0}.
        /// </summary>
        internal static string UserForm_LoadForm_Form_type_set_to___0_ {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Form_type_set_to___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading batch actions into application.
        /// </summary>
        internal static string UserForm_LoadForm_Loading_batch_actions_into_application {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Loading_batch_actions_into_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading form file from: {0}.
        /// </summary>
        internal static string UserForm_LoadForm_Loading_form_file_from___0_ {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Loading_form_file_from___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting form loading.
        /// </summary>
        internal static string UserForm_LoadForm_Starting_form_loading {
            get {
                return ResourceManager.GetString("UserForm_LoadForm_Starting_form_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing form with UID: {0}.
        /// </summary>
        internal static string UserForm_Refresh_Refreshing_form_with_UID___0_ {
            get {
                return ResourceManager.GetString("UserForm_Refresh_Refreshing_form_with_UID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting menu status for form with UID: {0}.
        /// </summary>
        internal static string UserForm_ResetMenuStatus_Resetting_menu_status_for_form_with_UID___0_ {
            get {
                return ResourceManager.GetString("UserForm_ResetMenuStatus_Resetting_menu_status_for_form_with_UID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing form to Width: {0}, Height: {1}.
        /// </summary>
        internal static string UserForm_Resize_Resizing_form_to_Width___0___Height___1_ {
            get {
                return ResourceManager.GetString("UserForm_Resize_Resizing_form_to_Width___0___Height___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting form with UID: {0}.
        /// </summary>
        internal static string UserForm_Select_Selecting_form_with_UID___0_ {
            get {
                return ResourceManager.GetString("UserForm_Select_Selecting_form_with_UID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to show form.
        /// </summary>
        internal static string UserForm_Show_Attempting_to_show_form {
            get {
                return ResourceManager.GetString("UserForm_Show_Attempting_to_show_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot show form because it is not alive.
        /// </summary>
        internal static string UserForm_Show_Cannot_show_form_because_it_is_not_alive {
            get {
                return ResourceManager.GetString("UserForm_Show_Cannot_show_form_because_it_is_not_alive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form displayed successfully.
        /// </summary>
        internal static string UserForm_Show_Form_displayed_successfully {
            get {
                return ResourceManager.GetString("UserForm_Show_Form_displayed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string UserForm_ShowWaitCursor_Loading___ {
            get {
                return ResourceManager.GetString("UserForm_ShowWaitCursor_Loading___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating form: {0}.
        /// </summary>
        internal static string UserForm_Update_Error_updating_form___0_ {
            get {
                return ResourceManager.GetString("UserForm_Update_Error_updating_form___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form updated successfully.
        /// </summary>
        internal static string UserForm_Update_Form_updated_successfully {
            get {
                return ResourceManager.GetString("UserForm_Update_Form_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating form with UID: {0}.
        /// </summary>
        internal static string UserForm_Update_Updating_form_with_UID___0_ {
            get {
                return ResourceManager.GetString("UserForm_Update_Updating_form_with_UID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during UserForm initialization:.
        /// </summary>
        internal static string UserForm_UserForm_Error_during_UserForm_initialization_ {
            get {
                return ResourceManager.GetString("UserForm_UserForm_Error_during_UserForm_initialization_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the construction of the UserForm.
        /// </summary>
        internal static string UserForm_UserForm_Starting_the_construction_of_the_UserForm {
            get {
                return ResourceManager.GetString("UserForm_UserForm_Starting_the_construction_of_the_UserForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserForm successfully initialized.
        /// </summary>
        internal static string UserForm_UserForm_UserForm_successfully_initialized {
            get {
                return ResourceManager.GetString("UserForm_UserForm_UserForm_successfully_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Description cannot exceed 30 characters. Provided length: {0}..
        /// </summary>
        internal static string UserTableAttribute_UserTableAttribute_Table_Description_cannot_exceed_30_characters__Provided_length___0__ {
            get {
                return ResourceManager.GetString("UserTableAttribute_UserTableAttribute_Table_Description_cannot_exceed_30_characte" +
                        "rs__Provided_length___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name cannot exceed 19 characters. Provided length: {0}..
        /// </summary>
        internal static string UserTableAttribute_UserTableAttribute_Table_Name_cannot_exceed_19_characters__Provided_length___0__ {
            get {
                return ResourceManager.GetString("UserTableAttribute_UserTableAttribute_Table_Name_cannot_exceed_19_characters__Pro" +
                        "vided_length___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with UserTableAttribute..
        /// </summary>
        internal static string UserTableAttributeNotFound_UserTableAttributeNotFound__0__is_not_decorated_with_UserTableAttribute_ {
            get {
                return ResourceManager.GetString("UserTableAttributeNotFound_UserTableAttributeNotFound__0__is_not_decorated_with_U" +
                        "serTableAttribute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 80 characters. Provided length: {0}..
        /// </summary>
        internal static string UserTableFieldAttributeBase_Description_Description_cannot_exceed_80_characters__Provided_length___0__ {
            get {
                return ResourceManager.GetString("UserTableFieldAttributeBase_Description_Description_cannot_exceed_80_characters__" +
                        "Provided_length___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 50 characters. Provided length: {0}..
        /// </summary>
        internal static string UserTableFieldAttributeBase_Name_Name_cannot_exceed_50_characters__Provided_length___0__ {
            get {
                return ResourceManager.GetString("UserTableFieldAttributeBase_Name_Name_cannot_exceed_50_characters__Provided_lengt" +
                        "h___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTableObjectModel.GetAll Method not found.
        /// </summary>
        internal static string UserTableMetadataCache_GetAllMethodInfo_UserTableObjectModel_GetAll_Method_not_found {
            get {
                return ResourceManager.GetString("UserTableMetadataCache_GetAllMethodInfo_UserTableObjectModel_GetAll_Method_not_fo" +
                        "und", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to add {0} into table {1} with Code: {2}.
        /// </summary>
        internal static string UserTableObjectModel_Add_Attempting_to_add__0__into_table__1__with_Code___2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Add_Attempting_to_add__0__into_table__1__with_Code___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from table {1} with Code {2} does not exist..
        /// </summary>
        internal static string UserTableObjectModel_Delete__0__from_table__1__with_Code__2__does_not_exist_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Delete__0__from_table__1__with_Code__2__does_not_exist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from table {1} with Code {3} deleted successfully..
        /// </summary>
        internal static string UserTableObjectModel_Delete__0__from_table__1__with_Code__3__deleted_successfully_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Delete__0__from_table__1__with_Code__3__deleted_successfully" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to delete {0} from table {1} with Code: {2}.
        /// </summary>
        internal static string UserTableObjectModel_Delete_Attempting_to_delete__0__from_table__1__with_Code___2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Delete_Attempting_to_delete__0__from_table__1__with_Code___2" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete {0} from table {1} with Code {2}. SAP Error Code: {3}. SAP Error Message: {4}.
        /// </summary>
        internal static string UserTableObjectModel_Delete_Failed_to_delete__0__from_table__1__with_Code__2___SAP_Error_Code___3___SAP_Error_Message___4_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Delete_Failed_to_delete__0__from_table__1__with_Code__2___SA" +
                        "P_Error_Code___3___SAP_Error_Message___4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from table {1} found in {0}, populating properties....
        /// </summary>
        internal static string UserTableObjectModel_Get__0__from_table__1__found_in__0___populating_properties___ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Get__0__from_table__1__found_in__0___populating_properties__" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from table {1} not found with Code: {2}.
        /// </summary>
        internal static string UserTableObjectModel_Get__0__from_table__1__not_found_with_Code___2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Get__0__from_table__1__not_found_with_Code___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully populated for Code: {1}.
        /// </summary>
        internal static string UserTableObjectModel_Get__0__successfully_populated_for_Code___1_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Get__0__successfully_populated_for_Code___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching {0} from table {1} with Code: {2}.
        /// </summary>
        internal static string UserTableObjectModel_Get_Fetching__0__from_table__1__with_Code___2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Get_Fetching__0__from_table__1__with_Code___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching {0} with Code: {1}.
        /// </summary>
        internal static string UserTableObjectModel_Get_Fetching__0__with_Code___1_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Get_Fetching__0__with_Code___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTableAttribute not found in {0}.
        /// </summary>
        internal static string UserTableObjectModel_Get_UserTableAttribute_not_found_in__0_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Get_UserTableAttribute_not_found_in__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing query: {0}.
        /// </summary>
        internal static string UserTableObjectModel_GetAll_Executing_query___0_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_GetAll_Executing_query___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching All {0}.
        /// </summary>
        internal static string UserTableObjectModel_GetAll_Fetching_All__0_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_GetAll_Fetching_All__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching all {0} from table {1}.
        /// </summary>
        internal static string UserTableObjectModel_GetAll_Fetching_all__0__from_table__1_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_GetAll_Fetching_all__0__from_table__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTableAttribute not found in {0}.
        /// </summary>
        internal static string UserTableObjectModel_GetAll_UserTableAttribute_not_found_in__0_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_GetAll_UserTableAttribute_not_found_in__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing field: {0}.{1} = {2}.
        /// </summary>
        internal static string UserTableObjectModel_PopulateFields_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_PopulateFields_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing field: {0}.{1}.
        /// </summary>
        internal static string UserTableObjectModel_PopulateFields_Processing_field___0___1_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_PopulateFields_Processing_field___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverting {0} Code to: {1}.
        /// </summary>
        internal static string UserTableObjectModel_RestoreOriginalCode_Reverting__0__Code_to___1_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_RestoreOriginalCode_Reverting__0__Code_to___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from table {1} with Code {2} saved successfully..
        /// </summary>
        internal static string UserTableObjectModel_Save__0__from_table__1__with_Code__2__saved_successfully_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save__0__from_table__1__with_Code__2__saved_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign value to field {0}: {1}.
        /// </summary>
        internal static string UserTableObjectModel_Save_Failed_to_assign_value_to_field__0____1_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save_Failed_to_assign_value_to_field__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save {0} in table {1} with Code {2}. SAP Error Code: {3}. SAP Error Message: {4}.
        /// </summary>
        internal static string UserTableObjectModel_Save_Failed_to_save__0__in_table__1__with_Code__2___SAP_Error_Code___3___SAP_Error_Message___4_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save_Failed_to_save__0__in_table__1__with_Code__2___SAP_Erro" +
                        "r_Code___3___SAP_Error_Message___4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting new {0} into table {1} with Code: {2}.
        /// </summary>
        internal static string UserTableObjectModel_Save_Inserting_new__0__into_table__1__with_Code___2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save_Inserting_new__0__into_table__1__with_Code___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for field {0}: {1}.
        /// </summary>
        internal static string UserTableObjectModel_Save_Invalid_value_for_field__0____1_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save_Invalid_value_for_field__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed field {0} = {1}.
        /// </summary>
        internal static string UserTableObjectModel_Save_Processed_field__0_____1_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save_Processed_field__0_____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0} into table {1} with Code: {2}.
        /// </summary>
        internal static string UserTableObjectModel_Save_Saving__0__into_table__1__with_Code___2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save_Saving__0__into_table__1__with_Code___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating existing {0} in table {1} with Code: {2}.
        /// </summary>
        internal static string UserTableObjectModel_Save_Updating_existing__0__in_table__1__with_Code___2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save_Updating_existing__0__in_table__1__with_Code___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating {0}&apos;s field {1} = {2}.
        /// </summary>
        internal static string UserTableObjectModel_Save_Validating__0__s_field__1_____2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Save_Validating__0__s_field__1_____2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to update {0} in table {1} with Code: {2}.
        /// </summary>
        internal static string UserTableObjectModel_Update_Attempting_to_update__0__in_table__1__with_Code___2_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Update_Attempting_to_update__0__in_table__1__with_Code___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving SAP User Table &apos;{0}&apos;....
        /// </summary>
        internal static string UserTableObjectModel_Update_Retrieving_SAP_User_Table___0_____ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_Update_Retrieving_SAP_User_Table___0_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing UserTableObjectModel....
        /// </summary>
        internal static string UserTableObjectModel_UserTableObjectModel_Initializing_UserTableObjectModel___ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_UserTableObjectModel_Initializing_UserTableObjectModel___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTableAttribute initialized: {0}.
        /// </summary>
        internal static string UserTableObjectModel_UserTableObjectModel_UserTableAttribute_initialized___0_ {
            get {
                return ResourceManager.GetString("UserTableObjectModel_UserTableObjectModel_UserTableAttribute_initialized___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add `{0} - {1}` to ValidValues.
        /// </summary>
        internal static string ValidValuesExtension_AddRange_Could_not_add__0___1__to_ValidValues {
            get {
                return ResourceManager.GetString("ValidValuesExtension_AddRange_Could_not_add__0___1__to_ValidValues", resourceCulture);
            }
        }
    }
}
